// ============================================
// FILE: Controllers/ImageGenerationController.cs
// PURPOSE: API Controller for Nano Banana Image Generation - RETURNS ACTUAL IMAGES
// ============================================

using Microsoft.AspNetCore.Mvc;
using Real_Time_Code_Reader.BLL.Services;

namespace Real_Time_Code_Reader.Controllers
{
    /// <summary>
    /// Request models for image generation endpoints
    /// </summary>
    public class ConceptVisualizationRequest
    {
        public string Concept { get; set; } = string.Empty;
        public string StudentLevel { get; set; } = "beginner";
    }

    public class CodeFlowchartRequest
    {
        public string Code { get; set; } = string.Empty;
        public string Language { get; set; } = string.Empty;
    }

    public class InfographicRequest
    {
        public string Topic { get; set; } = string.Empty;
        public string Style { get; set; } = "modern";
    }

    public class CheatSheetRequest
    {
        public string Topic { get; set; } = string.Empty;
        public string Language { get; set; } = string.Empty;
    }

    /// <summary>
    /// Controller for Gemini Nano Banana image generation endpoints
    /// Returns actual PNG images generated by Gemini
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class ImageGenerationController : ControllerBase
    {
        private readonly INanoBananaService _nanoBananaService;
        private readonly ILogger<ImageGenerationController> _logger;

        public ImageGenerationController(
            INanoBananaService nanoBananaService,
            ILogger<ImageGenerationController> logger)
        {
            _nanoBananaService = nanoBananaService;
            _logger = logger;
        }

        /// <summary>
        /// Health check endpoint
        /// </summary>
        [HttpGet("health")]
        public IActionResult Health()
        {
            return Ok(new
            {
                status = "healthy",
                service = "NanoBanana Image Generation",
                timestamp = DateTime.UtcNow,
                models = new
                {
                    flash = "gemini-2.5-flash-image",
                    pro = "gemini-3-pro-image-preview"
                }
            });
        }

        /// <summary>
        /// Generate a visual representation of a programming concept
        /// Returns: PNG image
        /// </summary>
        [HttpPost("visualize-concept")]
        public async Task<IActionResult> VisualizeConceptAsync([FromBody] ConceptVisualizationRequest request)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(request.Concept))
                {
                    return BadRequest(new { error = "Concept is required" });
                }

                _logger.LogInformation("Generating concept visualization for: {Concept}", request.Concept);

                var imageBytes = await _nanoBananaService.GenerateConceptVisualizationAsync(
                    request.Concept,
                    request.StudentLevel);

                // Return as PNG image
                return File(imageBytes, "image/png", $"concept_{DateTime.Now:yyyyMMddHHmmss}.png");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating concept visualization");
                return StatusCode(500, new
                {
                    error = "Failed to generate concept visualization",
                    message = ex.Message
                });
            }
        }

        /// <summary>
        /// Generate a flowchart from code
        /// Returns: PNG image
        /// </summary>
        [HttpPost("generate-flowchart")]
        public async Task<IActionResult> GenerateFlowchartAsync([FromBody] CodeFlowchartRequest request)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(request.Code))
                {
                    return BadRequest(new { error = "Code is required" });
                }

                if (string.IsNullOrWhiteSpace(request.Language))
                {
                    return BadRequest(new { error = "Language is required" });
                }

                _logger.LogInformation("Generating flowchart for {Language} code", request.Language);

                var imageBytes = await _nanoBananaService.GenerateCodeFlowchartAsync(
                    request.Code,
                    request.Language);

                // Return as PNG image
                return File(imageBytes, "image/png", $"flowchart_{DateTime.Now:yyyyMMddHHmmss}.png");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating flowchart");
                return StatusCode(500, new
                {
                    error = "Failed to generate flowchart",
                    message = ex.Message
                });
            }
        }

        /// <summary>
        /// Generate an educational infographic
        /// Returns: PNG image
        /// </summary>
        [HttpPost("generate-infographic")]
        public async Task<IActionResult> GenerateInfographicAsync([FromBody] InfographicRequest request)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(request.Topic))
                {
                    return BadRequest(new { error = "Topic is required" });
                }

                _logger.LogInformation("Generating infographic for topic: {Topic}", request.Topic);

                var imageBytes = await _nanoBananaService.GenerateInfographicAsync(
                    request.Topic,
                    request.Style);

                // Return as PNG image
                return File(imageBytes, "image/png", $"infographic_{DateTime.Now:yyyyMMddHHmmss}.png");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating infographic");
                return StatusCode(500, new
                {
                    error = "Failed to generate infographic",
                    message = ex.Message
                });
            }
        }

        /// <summary>
        /// Generate a programming language cheat sheet
        /// Returns: PNG image
        /// </summary>
        [HttpPost("generate-cheatsheet")]
        public async Task<IActionResult> GenerateCheatSheetAsync([FromBody] CheatSheetRequest request)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(request.Topic))
                {
                    return BadRequest(new { error = "Topic is required" });
                }

                if (string.IsNullOrWhiteSpace(request.Language))
                {
                    return BadRequest(new { error = "Language is required" });
                }

                _logger.LogInformation("Generating cheat sheet for {Language} - {Topic}",
                    request.Language, request.Topic);

                var imageBytes = await _nanoBananaService.GenerateCheatSheetAsync(
                    request.Topic,
                    request.Language);

                // Return as PNG image
                return File(imageBytes, "image/png", $"cheatsheet_{DateTime.Now:yyyyMMddHHmmss}.png");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating cheat sheet");
                return StatusCode(500, new
                {
                    error = "Failed to generate cheat sheet",
                    message = ex.Message
                });
            }
        }
    }
}
